################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

[package]
description = "Zenoh Rust Client library implementation of the Eclipse uProtocol"
edition = "2021"
exclude = [
    "tests/*",
    ".github/*",
    ".gitignore",
]
keywords = ["uProtocol", "SDK", "Zenoh"]
license = "Apache-2.0"
name = "up-client-zenoh"
readme = "README.md"
repository = "https://github.com/eclipse-uprotocol/up-client-zenoh-rust"
rust-version = "1.74.0"
version = "0.1.0"

[lints.clippy]
all = "deny"
pedantic = "deny"
#cargo = "deny"
#restriction = "deny"
#nursery = "deny"

[dependencies]
anyhow = "1.0.75"
tokio = { version = "1.35.1", default-features = false }
async-trait = "0.1"
chrono = "0.4.31"
crossbeam-channel = "0.5.12"
env_logger = "0.10.0"
log = "0.4.17"
prost = "0.12"
prost-types = "0.12"
protobuf = { version = "3.3" }
rand = "0.8.5"
up-rust = { git = "https://github.com/eclipse-uprotocol/up-rust", rev = "1bb08ba7a3666e58c316489fbcf3da3e29dee611" }
zenoh = { version = "0.11.0-rc.3", features = ["unstable"]}

[dev-dependencies]
test-case = { version = "3.3" }
