# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: nextest

on:
  workflow_call:
    outputs:
      test_results_url:
        description: 'URL of the test result artifact'
        value: ${{ jobs.coverage.outputs.test_results_url }}
  workflow_dispatch:

env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  CARGO_TERM_COLOR: always

jobs:
  nextest:
    outputs:
      test_results_url: ${{ steps.test_results.outputs.artifact-url }}
    runs-on: ubuntu-latest
    env: 
      NEXTEST_EXPERIMENTAL_LIBTEST_JSON: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      # Using nextest because it's faster than built-in test
      - uses: taiki-e/install-action@nextest
      - name: Run cargo nextest
        run: |
          cargo nextest run --message-format libtest-json-plus > testresults.json

      - name: Upload all-features test results artifact
        id: test_results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: testresults.json 
