# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: Test and Build docs

on:
  workflow_call:
    outputs:
      doctest_results_url:
        description: "URL of the doctest results artifact"
        value: ${{ jobs.doctest.outputs.test_results_url }}
  workflow_dispatch:

env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  CARGO_TERM_COLOR: always

jobs:
  test-build-docs:
    outputs:
      test_results_url: ${{ steps.doctest_results.outputs.artifact-url }}
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Run doc tests
        run: |
          RUSTC_BOOTSTRAP=1 cargo test --doc -- -Z unstable-options --format json --report-time > doctestresults.json
      - name: Upload doctest results artifact
        id: doctest_results
        uses: actions/upload-artifact@v4
        with:
          name: doctest-results
          path: doctestresults.json
      - name: Create Documentation
        run: |
          cargo doc --no-deps
